# Generated by Django 4.0.4 on 2022-04-23 09:02

from django.db import migrations, models

import app.hotels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("location", models.CharField(db_index=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(upload_to=app.hotels.models.photo_directory_path),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
