# Generated by Django 4.0.4 on 2022-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
