# Generated by Django 4.0.4 on 2022-04-23 10:04

from django.db import migrations, models
import app.hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="photo",
            field=models.ImageField(
                unique=True, upload_to=app.hotels.models.photo_directory_path
            ),
        ),
    ]
