# Generated by Django 4.0.4 on 2022-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_alter_hotel_name_alter_hotel_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="slug",
            field=models.SlugField(default=None, null=True),
        ),
    ]
