# Generated by Django 4.0.4 on 2022-04-24 10:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_alter_hotel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
