# Generated by Django 4.0.4 on 2024-01-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0007_alter_hotel_location_alter_hotel_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=250)),
                ("phone", models.CharField(blank=True, max_length=250)),
                ("website", models.URLField(blank=True, max_length=250)),
                ("sales_contact", models.CharField(blank=True, max_length=250)),
                (
                    "price_range",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
