# Generated by Django 4.0.4 on 2024-01-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0008_hotelchain"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelchain",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="email",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
