# Generated by Django 4.0.4 on 2024-01-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0009_hotelchain_description_alter_hotelchain_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelchain",
            options={},
        ),
        migrations.AddField(
            model_name="hotel",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hotels.hotelchain",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="related_hotels",
            field=models.ManyToManyField(blank=True, null=True, to="hotels.hotel"),
        ),
    ]
