# Generated by Django 4.0.4 on 2024-04-13 14:48

import app.config.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0013_alter_hotel_options_alter_hotelchain_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hotels.hotelchain",
                verbose_name="Chain",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.CharField(
                db_index=True, max_length=50, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="photo",
            field=models.ImageField(
                upload_to=app.config.utils.photo_directory_path, verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="related_hotels",
            field=models.ManyToManyField(
                blank=True, to="hotels.hotel", verbose_name="Related Hotels"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="email",
            field=models.EmailField(blank=True, max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="price_range",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                null=True,
                verbose_name="Price Range",
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="sales_contact",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Sales Contact"
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="website",
            field=models.URLField(blank=True, max_length=250, verbose_name="Website"),
        ),
    ]
