# Generated by Django 4.0.4 on 2024-04-13 15:35

import app.config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0014_alter_hotel_chain_alter_hotel_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to=app.config.utils.photo_directory_path,
                verbose_name="Photo",
            ),
        ),
    ]
