# Generated by Django 4.0.4 on 2024-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0015_alter_hotel_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelchain",
            name="price_range",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                default=2,
                verbose_name="Price Range",
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="title",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Title"
            ),
        ),
    ]
