# Generated by Django 4.0.4 on 2024-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0017_hotelchain_created_at_hotelchain_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelchain",
            name="title",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Title"),
        ),
    ]
