# Generated by Django 4.0.4 on 2024-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0022_remove_hoteldraft_related_hotels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.CharField(
                choices=[
                    ("madrid", "Madrid"),
                    ("barcelona", "Barcelona"),
                    ("sevilla", "Sevilla"),
                ],
                db_index=True,
                default="madrid",
                max_length=50,
                null=True,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="hoteldraft",
            name="location",
            field=models.CharField(
                choices=[
                    ("madrid", "Madrid"),
                    ("barcelona", "Barcelona"),
                    ("sevilla", "Sevilla"),
                ],
                db_index=True,
                default="madrid",
                max_length=50,
                null=True,
                verbose_name="Location",
            ),
        ),
    ]
